"""
This type stub file was generated by pyright.
"""

from .api import *
from .jm_plugin import *

__version__ = ...
gb = ...
def register_jmcomic_component(variables: Dict[str, Any], method, valid_interface: type): # -> None:
    ...

