"""
This type stub file was generated by pyright.
"""

from .jm_downloader import *

__DOWNLOAD_API_RET = Tuple[JmAlbumDetail, JmDownloader]
def download_batch(download_api, jm_id_iter: Union[Iterable, Generator], option=..., downloader=...) -> Set[__DOWNLOAD_API_RET]:
    """
    批量下载 album / photo

    一个album/photo，对应一个线程，对应一个option

    :param download_api: 下载api
    :param jm_id_iter: jmid (album_id, photo_id) 的迭代器
    :param option: 下载选项，所有的jmid共用一个option
    :param downloader: 下载器类
    """
    ...

def download_album(jm_album_id, option=..., downloader=..., callback=..., check_exception=...) -> Union[__DOWNLOAD_API_RET, Set[__DOWNLOAD_API_RET]]:
    """
    下载一个本子（album），包含其所有的章节（photo）

    当jm_album_id不是str或int时，视为批量下载，相当于调用 download_batch(download_album, jm_album_id, option, downloader)

    :param jm_album_id: 本子的禁漫车号
    :param option: 下载选项
    :param downloader: 下载器类
    :param callback: 返回值回调函数，可以拿到 album 和 downloader
    :param check_exception: 是否检查异常, 如果为True，会检查downloader是否有下载异常，并上抛PartialDownloadFailedException
    :return: 对于的本子实体类，下载器（如果是上述的批量情况，返回值为download_batch的返回值）
    """
    ...

def download_photo(jm_photo_id, option=..., downloader=..., callback=..., check_exception=...): # -> Set[__DOWNLOAD_API_RET] | tuple[JmPhotoDetail, JmDownloader]:
    """
    下载一个章节（photo），参数同 download_album
    """
    ...

def new_downloader(option=..., downloader=...) -> JmDownloader:
    ...

def create_option_by_file(filepath): # -> JmOption:
    ...

def create_option_by_env(env_name=...): # -> JmOption:
    ...

def create_option_by_str(text: str, mode=...): # -> JmOption:
    ...

create_option = ...
