"""
This type stub file was generated by pyright.
"""

"""
command-line usage

for example, download album 123 456, photo 333:

$ jmcomic 123 456 p333 --option="D:/option.yml"


"""
def get_env(name, default): # -> str:
    ...

class JmcomicUI:
    def __init__(self) -> None:
        ...
    
    def parse_arg(self): # -> None:
        ...
    
    def parse_raw_id(self): # -> None:
        ...
    
    def main(self): # -> None:
        ...
    
    def run(self, option): # -> None:
        ...
    


def main(): # -> None:
    ...

