"""
This type stub file was generated by pyright.
"""

from .jm_toolkit import *

class JmResp:
    def __init__(self, resp) -> None:
        ...
    
    @property
    def is_success(self) -> bool:
        ...
    
    @property
    def is_not_success(self) -> bool:
        ...
    
    @property
    def content(self):
        ...
    
    @property
    def http_code(self):
        ...
    
    @property
    def text(self) -> str:
        ...
    
    @property
    def url(self) -> str:
        ...
    
    def require_success(self): # -> None:
        ...
    
    def error_msg(self): # -> str:
        ...
    


class JmImageResp(JmResp):
    def error_msg(self): # -> str:
        ...
    
    def transfer_to(self, path, scramble_id, decode_image=..., img_url=...): # -> None:
        ...
    


class JmJsonResp(JmResp):
    @field_cache()
    def json(self) -> Dict:
        ...
    
    def model(self) -> AdvancedDict:
        ...
    


class JmApiResp(JmJsonResp):
    def __init__(self, resp, ts: str) -> None:
        ...
    
    @field_cache()
    def json(self) -> Dict:
        ...
    
    @property
    def is_success(self) -> bool:
        ...
    
    @property
    @field_cache()
    def decoded_data(self) -> str:
        ...
    
    @property
    def encoded_data(self) -> str:
        ...
    
    @property
    def res_data(self) -> Any:
        ...
    
    @property
    def model_data(self) -> AdvancedDict:
        ...
    


class JmAlbumCommentResp(JmJsonResp):
    def is_success(self) -> bool:
        ...
    


class JmDetailClient:
    def get_album_detail(self, album_id) -> JmAlbumDetail:
        ...
    
    def get_photo_detail(self, photo_id, fetch_album=..., fetch_scramble_id=...) -> JmPhotoDetail:
        ...
    
    def check_photo(self, photo: JmPhotoDetail): # -> None:
        """
        photo来源有两种:
        1. album[?]
        2. client.get_photo_detail(?)

        其中，只有[2]是可以包含下载图片的url信息的。
        本方法会检查photo是不是[1]，
        如果是[1]，通过请求获取[2]，然后把2中的一些重要字段更新到1中

        :param photo: 被检查的JmPhotoDetail对象
        """
        ...
    


class JmUserClient:
    def login(self, username: str, password: str):
        """
        1. 返回response响应对象
        2. 保证当前client拥有登录cookies
        """
        ...
    
    def album_comment(self, video_id, comment, originator=..., status=..., comment_id=..., **kwargs) -> JmAlbumCommentResp:
        """
        评论漫画/评论回复
        :param video_id: album_id/photo_id
        :param comment: 评论内容
        :param status: 是否 "有劇透"
        :param comment_id: 被回复评论的id
        :param originator:
        :returns: JmAcResp 对象
        """
        ...
    
    def favorite_folder(self, page=..., order_by=..., folder_id=..., username=...) -> JmFavoritePage:
        """
        获取收藏了的漫画，文件夹默认是全部
        :param folder_id: 文件夹id
        :param page: 分页
        :param order_by: 排序
        :param username: 用户名
        """
        ...
    
    def add_favorite_album(self, album_id, folder_id=...):
        """
        把漫画加入收藏夹
        """
        ...
    


class JmImageClient:
    def download_image(self, img_url: str, img_save_path: str, scramble_id: Optional[int] = ..., decode_image=...): # -> None:
        """
        下载JM的图片
        :param img_url: 图片url
        :param img_save_path: 图片保存位置
        :param scramble_id: 图片所在photo的scramble_id
        :param decode_image: 要保存的是解密后的图还是原图
        """
        ...
    
    def save_image_resp(self, decode_image, img_save_path, img_url, resp, scramble_id): # -> None:
        ...
    
    def download_by_image_detail(self, image: JmImageDetail, img_save_path, decode_image=...): # -> None:
        ...
    
    def get_jm_image(self, img_url) -> JmImageResp:
        ...
    
    @classmethod
    def img_is_not_need_to_decode(cls, data_original: str, _resp) -> bool:
        ...
    
    def download_album_cover(self, album_id, save_path: str, size: str = ...): # -> None:
        ...
    


class JmSearchAlbumClient:
    """
    搜尋的最佳姿勢？
    【包含搜尋】
    搜尋[+]全彩[空格][+]人妻,僅顯示全彩且是人妻的本本
    範例:+全彩 +人妻

    【排除搜尋】
    搜尋全彩[空格][-]人妻,顯示全彩並排除人妻的本本
    範例:全彩 -人妻

    【我都要搜尋】
    搜尋全彩[空格]人妻,會顯示所有包含全彩及人妻的本本
    範例:全彩 人妻
    """
    def search(self, search_query: str, page: int, main_tag: int, order_by: str, time: str, category: str, sub_category: Optional[str]) -> JmSearchPage:
        """
        搜索【成人A漫】
        网页端与移动端的搜索有差别：

        - 移动端不支持 category, sub_category参数，网页端支持全部参数
        """
        ...
    
    def search_site(self, search_query: str, page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        对应禁漫的站内搜索
        """
        ...
    
    def search_work(self, search_query: str, page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        搜索album的作品 work
        """
        ...
    
    def search_author(self, search_query: str, page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        搜索album的作者 author
        """
        ...
    
    def search_tag(self, search_query: str, page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        搜索album的标签 tag
        """
        ...
    
    def search_actor(self, search_query: str, page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        搜索album的登场角色 actor
        """
        ...
    


class JmCategoryClient:
    """
    该接口可以看作是对全体禁漫本子的排行，热门排行的功能也派生于此

    月排行 = 分类【时间=月，排序=观看】
    周排行 = 分类【时间=周，排序=观看】
    日排行 = 分类【时间=周，排序=观看】
    """
    def categories_filter(self, page: int, time: str, category: str, order_by: str, sub_category: Optional[str] = ...) -> JmCategoryPage:
        """
        分类

        :param page: 页码
        :param time: 时间范围，默认是全部时间
        :param category: 类别，默认是最新，即显示最新的禁漫本子
        :param sub_category: 副分类，仅网页端有这功能
        :param order_by: 排序方式，默认是观看数
        """
        ...
    
    def month_ranking(self, page: int, category: str = ...): # -> JmCategoryPage:
        """
        月排行 = 分类【时间=月，排序=观看】
        """
        ...
    
    def week_ranking(self, page: int, category: str = ...): # -> JmCategoryPage:
        """
        周排行 = 分类【时间=周，排序=观看】
        """
        ...
    
    def day_ranking(self, page: int, category: str = ...): # -> JmCategoryPage:
        """
        日排行 = 分类【时间=日，排序=观看】
        """
        ...
    


class JmcomicClient(JmImageClient, JmDetailClient, JmUserClient, JmSearchAlbumClient, JmCategoryClient, Postman):
    client_key: None
    def get_domain_list(self) -> List[str]:
        """
        获取当前client的域名配置
        """
        ...
    
    def set_domain_list(self, domain_list: List[str]):
        """
        设置当前client的域名配置
        """
        ...
    
    def set_cache_dict(self, cache_dict: Optional[Dict]):
        ...
    
    def get_cache_dict(self) -> Optional[Dict]:
        ...
    
    def of_api_url(self, api_path, domain):
        ...
    
    def get_html_domain(self): # -> str | Any:
        ...
    
    def get_html_domain_all(self): # -> List[str]:
        ...
    
    def get_html_domain_all_via_github(self): # -> set[Any]:
        ...
    
    def do_page_iter(self, params: dict, page: int, get_page_method): # -> Generator[Any, Any, None]:
        ...
    
    def favorite_folder_gen(self, page=..., order_by=..., folder_id=..., username=...) -> Generator[JmFavoritePage, Dict, None]:
        """
        见 search_gen
        """
        ...
    
    def search_gen(self, search_query: str, main_tag=..., page: int = ..., order_by: str = ..., time: str = ..., category: str = ..., sub_category: Optional[str] = ...) -> Generator[JmSearchPage, Dict, None]:
        """
        搜索结果的生成器，支持下面这种调用方式：

        ```
        for page in self.search_gen('无修正'):
            # 每次循环，page为新页的结果
            pass
        ```

        同时支持外界send参数，可以改变搜索的设定，例如：

        ```
        gen = client.search_gen('MANA')
        for i, page in enumerate(gen):
            print(page.page_count)
            page = gen.send({
                'search_query': '+MANA +无修正',
                'page': 1
            })
            print(page.page_count)
            break
        ```

        """
        ...
    
    def categories_filter_gen(self, page: int = ..., time: str = ..., category: str = ..., order_by: str = ..., sub_category: Optional[str] = ...) -> Generator[JmCategoryPage, Dict, None]:
        """
        见 search_gen
        """
        ...
    
    def is_given_type(self, ctype: Type[JmcomicClient]) -> bool:
        """
        Client代理的此方法会被路由到内部client的方法
        即：ClientProxy(AClient()).is_given_type(AClient) is True
        但是: ClientProxy(AClient()).client_key != AClient.client_key
        """
        ...
    


