"""
This type stub file was generated by pyright.
"""

from .jm_client_interface import *

class AbstractJmClient(JmcomicClient, PostmanProxy):
    client_key = ...
    func_to_cache = ...
    def __init__(self, postman: Postman, domain_list: List[str], retry_times=..., domain_retry_strategy=...) -> None:
        """
        创建JM客户端

        :param postman: 负责实现HTTP请求的对象，持有cookies、headers、proxies等信息
        :param domain_list: 禁漫域名
        :param retry_times: 重试次数
        """
        ...
    
    def after_init(self): # -> None:
        ...
    
    def get(self, url, **kwargs): # -> JmImageResp:
        ...
    
    def post(self, url, **kwargs): # -> JmImageResp:
        ...
    
    def of_api_url(self, api_path, domain): # -> str:
        ...
    
    def get_jm_image(self, img_url) -> JmImageResp:
        ...
    
    def request_with_retry(self, request, url, domain_index=..., retry_count=..., is_image=..., **kwargs): # -> JmImageResp:
        """
        支持重试和切换域名的机制

        如果url包含了指定域名，则不会切换域名，例如图片URL。

        如果需要拿到域名进行回调处理，可以重写 self.update_request_with_specify_domain 方法，例如更新headers

        :param request: 请求方法
        :param url: 图片url / path (/album/xxx)
        :param domain_index: 域名下标
        :param retry_count: 重试次数
        :param is_image: 是否是图片请求
        :param kwargs: 请求方法的kwargs
        """
        ...
    
    def raise_if_resp_should_retry(self, resp, is_image): # -> JmImageResp:
        """
        依然是回调，在最后返回之前，还可以判断resp是否重试
        """
        ...
    
    def update_request_with_specify_domain(self, kwargs: dict, domain: Optional[str], is_image: bool = ...): # -> None:
        """
        域名自动切换时，用于更新请求参数的回调
        """
        ...
    
    def log_topic(self): # -> None:
        ...
    
    def before_retry(self, e, kwargs, retry_count, url): # -> None:
        ...
    
    def enable_cache(self): # -> None:
        ...
    
    def set_cache_dict(self, cache_dict: Optional[Dict]): # -> None:
        ...
    
    def get_cache_dict(self): # -> Dict[Any, Any] | None:
        ...
    
    def get_domain_list(self): # -> List[str]:
        ...
    
    def set_domain_list(self, domain_list: List[str]): # -> None:
        ...
    
    def fallback(self, request, url, domain_index, retry_count, is_image, **kwargs):
        ...
    
    def append_params_to_url(self, url, params): # -> str:
        ...
    
    def decode(self, url: str): # -> str:
        ...
    


class JmHtmlClient(AbstractJmClient):
    client_key = ...
    func_to_cache = ...
    API_SEARCH = ...
    API_CATEGORY = ...
    def add_favorite_album(self, album_id, folder_id=...): # -> JmImageResp:
        ...
    
    def get_album_detail(self, album_id) -> JmAlbumDetail:
        ...
    
    def get_photo_detail(self, photo_id, fetch_album=..., fetch_scramble_id=...) -> JmPhotoDetail:
        ...
    
    def fetch_detail_entity(self, jmid, prefix): # -> JmAlbumDetail | JmPhotoDetail | None:
        ...
    
    def search(self, search_query: str, page: int, main_tag: int, order_by: str, time: str, category: str, sub_category: Optional[str]) -> JmSearchPage:
        """
        网页搜索API
        """
        ...
    
    @classmethod
    def build_search_url(cls, base: str, category: str, sub_category: Optional[str]): # -> str:
        """
        构建网页搜索/分类的URL

        示例：
        :param base: "/search/photos"
        :param category CATEGORY_DOUJIN
        :param sub_category SUB_DOUJIN_CG
        :return "/search/photos/doujin/sub/CG"
        """
        ...
    
    def categories_filter(self, page: int, time: str, category: str, order_by: str, sub_category: Optional[str] = ...) -> JmCategoryPage:
        ...
    
    def login(self, username, password, id_remember=..., login_remember=...): # -> JmImageResp:
        """
        返回response响应对象
        """
        ...
    
    def favorite_folder(self, page=..., order_by=..., folder_id=..., username=...) -> JmFavoritePage:
        ...
    
    def get_username_from_cookies(self) -> str:
        ...
    
    def get_jm_html(self, url, require_200=..., **kwargs): # -> JmImageResp:
        """
        请求禁漫网页的入口
        """
        ...
    
    def update_request_with_specify_domain(self, kwargs: dict, domain: Optional[str], is_image=...): # -> None:
        ...
    
    @classmethod
    def raise_request_error(cls, resp, msg: Optional[str] = ...):
        """
        请求如果失败，统一由该方法抛出异常
        """
        ...
    
    def album_comment(self, video_id, comment, originator=..., status=..., comment_id=..., **kwargs) -> JmAlbumCommentResp:
        ...
    
    @classmethod
    def require_resp_success_else_raise(cls, resp, url: str): # -> None:
        """
        :param resp: 响应对象
        :param url: /photo/12412312
        """
        ...
    
    @classmethod
    def check_special_text(cls, resp): # -> None:
        ...
    
    @classmethod
    def check_special_http_code(cls, resp): # -> None:
        ...
    


class JmApiClient(AbstractJmClient):
    client_key = ...
    func_to_cache = ...
    API_SEARCH = ...
    API_CATEGORIES_FILTER = ...
    API_ALBUM = ...
    API_CHAPTER = ...
    API_SCRAMBLE = ...
    API_FAVORITE = ...
    def search(self, search_query: str, page: int, main_tag: int, order_by: str, time: str, category: str, sub_category: Optional[str]) -> JmSearchPage:
        """
        移动端暂不支持 category和sub_category
        """
        ...
    
    def categories_filter(self, page: int, time: str, category: str, order_by: str, sub_category: Optional[str] = ...): # -> JmSearchPage:
        """
        移动端不支持 sub_category
        """
        ...
    
    def get_album_detail(self, album_id) -> JmAlbumDetail:
        ...
    
    def get_photo_detail(self, photo_id, fetch_album=..., fetch_scramble_id=...) -> JmPhotoDetail:
        ...
    
    def get_scramble_id(self, photo_id, album_id=...): # -> str | Any:
        """
        带有缓存的fetch_scramble_id，缓存位于 JmModuleConfig.SCRAMBLE_CACHE
        """
        ...
    
    def fetch_detail_entity(self, jmid, clazz): # -> Any | JmAlbumDetail:
        """
        请求实体类
        """
        ...
    
    def fetch_scramble_id(self, photo_id): # -> str | Any:
        """
        请求scramble_id
        """
        ...
    
    def fetch_photo_additional_field(self, photo: JmPhotoDetail, fetch_album: bool, fetch_scramble_id: bool): # -> None:
        """
        获取章节的额外信息
        1. scramble_id
        2. album
        如果都需要获取，会排队，效率低

        todo: 改进实现 (had polished by FutureClientProxy)
        1. 直接开两个线程跑
        2. 开两个线程，但是开之前检查重复性
        3. 线程池，也要检查重复性
        23做法要改不止一处地方
        """
        ...
    
    def setting(self) -> JmApiResp:
        """
        禁漫app的setting请求，返回如下内容（resp.res_data）
        {
          "logo_path": "https://cdn-msp.jmapiproxy1.monster/media/logo/new_logo.png",
          "main_web_host": "18-comic.work",
          "img_host": "https://cdn-msp.jmapiproxy1.monster",
          "base_url": "https://www.jmapinode.biz",
          "is_cn": 0,
          "cn_base_url": "https://www.jmapinode.biz",
          "version": "1.6.0",
          "test_version": "1.6.1",
          "store_link": "https://play.google.com/store/apps/details?id=com.jiaohua_browser",
          "ios_version": "1.6.0",
          "ios_test_version": "1.6.1",
          "ios_store_link": "https://18comic.vip/stray/",
          "ad_cache_version": 1698140798,
          "bundle_url": "https://18-comic.work/static/apk/patches1.6.0.zip",
          "is_hot_update": true,
          "api_banner_path": "https://cdn-msp.jmapiproxy1.monster/media/logo/channel_log.png?v=",
          "version_info": "\nAPP & IOS更新\nV1.6.0\n#禁漫 APK 更新拉!!\n更新調整以下項目\n1. 系統優化\n\nV1.5.9\n1. 跳錯誤新增 重試 網頁 按鈕\n2. 圖片讀取優化\n3.
          線路調整優化\n\n無法順利更新或是系統題是有風險請使用下方\n下載點2\n有問題可以到DC群反饋\nhttps://discord.gg/V74p7HM\n",
          "app_shunts": [
            {
              "title": "圖源1",
              "key": 1
            },
            {
              "title": "圖源2",
              "key": 2
            },
            {
              "title": "圖源3",
              "key": 3
            },
            {
              "title": "圖源4",
              "key": 4
            }
          ],
          "download_url": "https://18-comic.work/static/apk/1.6.0.apk",
          "app_landing_page": "https://jm365.work/pXYbfA",
          "float_ad": true
        }
        """
        ...
    
    def login(self, username, password) -> JmApiResp:
        """
        {
          "uid": "123",
          "username": "x",
          "email": "x",
          "emailverified": "yes",
          "photo": "x",
          "fname": "",
          "gender": "x",
          "message": "Welcome x!",
          "coin": 123,
          "album_favorites": 123,
          "s": "x",
          "level_name": "x",
          "level": 1,
          "nextLevelExp": 123,
          "exp": "123",
          "expPercent": 123,
          "badges": [],
          "album_favorites_max": 123
        }

        """
        ...
    
    def favorite_folder(self, page=..., order_by=..., folder_id=..., username=...) -> JmFavoritePage:
        ...
    
    def add_favorite_album(self, album_id, folder_id=...): # -> JmApiResp:
        """
        移动端没有提供folder_id参数
        """
        ...
    
    def require_resp_status_ok(self, resp: JmApiResp): # -> None:
        """
        检查返回数据中的status字段是否为ok
        """
        ...
    
    def req_api(self, url, get=..., require_success=..., **kwargs) -> JmApiResp:
        ...
    
    def update_request_with_specify_domain(self, kwargs: dict, domain: Optional[str], is_image=...): # -> None:
        ...
    
    def decide_headers_and_ts(self, kwargs, url): # -> int:
        ...
    
    @classmethod
    def require_resp_success(cls, resp: JmApiResp, url: Optional[str] = ...): # -> None:
        """

        :param resp: 响应对象
        :param url: 请求路径，例如 /setting
        """
        ...
    
    def raise_if_resp_should_retry(self, resp, is_image): # -> JmImageResp | JmResp:
        """
        该方法会判断resp返回值是否是json格式，
        如果不是，大概率是禁漫内部异常，需要进行重试

        由于完整的json格式校验会有性能开销，所以只做简单的检查，
        只校验第一个有效字符是不是 '{'，如果不是，就认为异常数据，需要重试
        """
        ...
    
    def after_init(self): # -> None:
        ...
    
    client_update_domain_lock = ...
    def req_api_domain_server(self, url): # -> Any | None:
        ...
    
    def update_api_domain(self): # -> None:
        ...
    
    client_init_cookies_lock = ...
    def ensure_have_cookies(self): # -> None:
        ...
    
    @field_cache("APP_COOKIES", obj=JmModuleConfig)
    def get_cookies(self): # -> dict[Any, Any]:
        ...
    


class PhotoConcurrentFetcherProxy(JmcomicClient):
    """
    为了解决 JmApiClient.get_photo_detail 方法的排队调用问题，
    即在访问完photo的接口后，需要另外排队访问获取album和scramble_id的接口。

    这三个接口可以并发请求，这样可以提高效率。

    此Proxy代理了get_photo_detail，实现了并发请求这三个接口，然后组装返回值返回photo。

    可通过插件 ClientProxyPlugin 启用本类，配置如下:
    ```yml
    plugins:
      after_init:
        - plugin: client_proxy
          kwargs:
            proxy_client_key: photo_concurrent_fetcher_proxy
    ```
    """
    client_key = ...
    class FutureWrapper:
        def __init__(self, future, after_done_callback) -> None:
            ...
        
        def result(self): # -> None:
            ...
        
    
    
    def __init__(self, client: JmcomicClient, max_workers=..., executors=...) -> None:
        ...
    
    def route_notimpl_method_to_internal_client(self, client): # -> None:
        ...
    
    def get_album_detail(self, album_id) -> JmAlbumDetail:
        ...
    
    def get_future(self, cache_key, task): # -> FutureWrapper:
        ...
    
    def get_photo_detail(self, photo_id, fetch_album=..., fetch_scramble_id=...) -> JmPhotoDetail:
        ...
    


