"""
This type stub file was generated by pyright.
"""

from .jm_option import *

def catch_exception(func): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    ...

class DownloadCallback:
    def before_album(self, album: JmAlbumDetail): # -> None:
        ...
    
    def after_album(self, album: JmAlbumDetail): # -> None:
        ...
    
    def before_photo(self, photo: JmPhotoDetail): # -> None:
        ...
    
    def after_photo(self, photo: JmPhotoDetail): # -> None:
        ...
    
    def before_image(self, image: JmImageDetail, img_save_path): # -> None:
        ...
    
    def after_image(self, image: JmImageDetail, img_save_path): # -> None:
        ...
    


class JmDownloader(DownloadCallback):
    """
    JmDownloader = JmOption + 调度逻辑
    """
    def __init__(self, option: JmOption) -> None:
        ...
    
    def download_album(self, album_id): # -> JmAlbumDetail:
        ...
    
    def download_by_album_detail(self, album: JmAlbumDetail): # -> None:
        ...
    
    def download_photo(self, photo_id): # -> JmPhotoDetail:
        ...
    
    @catch_exception
    def download_by_photo_detail(self, photo: JmPhotoDetail): # -> None:
        ...
    
    @catch_exception
    def download_by_image_detail(self, image: JmImageDetail): # -> None:
        ...
    
    def execute_on_condition(self, iter_objs: DetailEntity, apply: Callable, count_batch: int): # -> None:
        """
        调度本子/章节的下载
        """
        ...
    
    def do_filter(self, detail: DetailEntity): # -> DetailEntity:
        """
        该方法可用于过滤本子/章节，默认不会做过滤。
        例如:
        只想下载 本子的最新一章，返回 [album[-1]]
        只想下载 章节的前10张图片，返回 [photo[:10]]

        :param detail: 可能是本子或者章节，需要自行使用 isinstance / detail.is_xxx 判断
        :returns: 只想要下载的 本子的章节 或 章节的图片
        """
        ...
    
    @property
    def all_success(self) -> bool:
        """
        是否成功下载了全部图片

        该属性需要等到downloader的全部download_xxx方法完成后才有意义。

        注意！如果使用了filter机制，例如通过filter只下载3张图片，那么all_success也会为False
        """
        ...
    
    @property
    def has_download_failures(self): # -> bool:
        ...
    
    def before_album(self, album: JmAlbumDetail): # -> None:
        ...
    
    def after_album(self, album: JmAlbumDetail): # -> None:
        ...
    
    def before_photo(self, photo: JmPhotoDetail): # -> None:
        ...
    
    def after_photo(self, photo: JmPhotoDetail): # -> None:
        ...
    
    def before_image(self, image: JmImageDetail, img_save_path): # -> None:
        ...
    
    def after_image(self, image: JmImageDetail, img_save_path): # -> None:
        ...
    
    def raise_if_has_exception(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    @classmethod
    def use(cls, *args, **kwargs): # -> None:
        """
        让本类替换JmModuleConfig.CLASS_DOWNLOADER
        """
        ...
    


class DoNotDownloadImage(JmDownloader):
    """
    不会下载任何图片的Downloader，用作测试
    """
    def download_by_image_detail(self, image: JmImageDetail): # -> None:
        ...
    


class JustDownloadSpecificCountImage(JmDownloader):
    """
    只下载特定数量图片的Downloader，用作测试
    """
    count_lock = ...
    count = ...
    @catch_exception
    def download_by_image_detail(self, image: JmImageDetail): # -> None:
        ...
    
    def try_countdown(self): # -> bool:
        ...
    
    @classmethod
    def use(cls, count): # -> None:
        ...
    


