"""
This type stub file was generated by pyright.
"""

from .jm_entity import *

class JmcomicException(Exception):
    description = ...
    def __init__(self, msg: str, context: dict) -> None:
        ...
    
    def from_context(self, key):
        ...
    
    def __str__(self) -> str:
        ...
    


class ResponseUnexpectedException(JmcomicException):
    description = ...
    @property
    def resp(self):
        ...
    


class RegularNotMatchException(JmcomicException):
    description = ...
    @property
    def resp(self): # -> None:
        """
        可能为None
        """
        ...
    
    @property
    def error_text(self):
        ...
    
    @property
    def pattern(self):
        ...
    


class JsonResolveFailException(ResponseUnexpectedException):
    description = ...


class MissingAlbumPhotoException(ResponseUnexpectedException):
    description = ...
    @property
    def error_jmid(self) -> str:
        ...
    


class RequestRetryAllFailException(JmcomicException):
    description = ...


class PartialDownloadFailedException(JmcomicException):
    description = ...
    @property
    def downloader(self):
        ...
    


class ExceptionTool:
    """
    抛异常的工具
    1: 能简化 if-raise 语句的编写
    2: 有更好的上下文信息传递方式
    """
    CONTEXT_KEY_RESP = ...
    CONTEXT_KEY_HTML = ...
    CONTEXT_KEY_RE_PATTERN = ...
    CONTEXT_KEY_MISSING_JM_ID = ...
    CONTEXT_KEY_DOWNLOADER = ...
    @classmethod
    def raises(cls, msg: str, context: dict = ..., etype: Optional[Type[Exception]] = ...):
        """
        抛出异常

        :param msg: 异常消息
        :param context: 异常上下文数据
        :param etype: 异常类型，默认使用 JmcomicException
        """
        ...
    
    @classmethod
    def raises_regex(cls, msg: str, html: str, pattern: Pattern):
        ...
    
    @classmethod
    def raises_resp(cls, msg: str, resp, etype=...):
        ...
    
    @classmethod
    def raise_missing(cls, resp, jmid: str):
        """
        抛出本子/章节的异常
        :param resp: 响应对象
        :param jmid: 禁漫本子/章节id
        """
        ...
    
    @classmethod
    def require_true(cls, case: bool, msg: str): # -> None:
        ...
    
    @classmethod
    def replace_old_exception_executor(cls, raises: Callable[[Callable, str, dict], None]): # -> None:
        ...
    
    @classmethod
    def notify_all_listeners(cls, e): # -> None:
        ...
    


