"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from common import *
from .jm_config import *

class Downloadable:
    def __init__(self) -> None:
        ...
    


class JmBaseEntity:
    def to_file(self, filepath): # -> None:
        ...
    
    @classmethod
    def is_image(cls): # -> Literal[False]:
        ...
    
    @classmethod
    def is_photo(cls): # -> Literal[False]:
        ...
    
    @classmethod
    def is_album(cls): # -> Literal[False]:
        ...
    
    @classmethod
    def is_page(cls): # -> Literal[False]:
        ...
    


class IndexedEntity:
    def getindex(self, index: int):
        ...
    
    def __len__(self):
        ...
    
    def __getitem__(self, item) -> Any:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class DetailEntity(JmBaseEntity, IndexedEntity):
    @property
    def id(self) -> str:
        ...
    
    @property
    def title(self) -> str:
        ...
    
    @property
    def author(self):
        ...
    
    @property
    def oname(self) -> str:
        """
        oname = original name

        示例:

        title："喂我吃吧 老師! [欶瀾漢化組] [BLVEFO9] たべさせて、せんせい! (ブルーアーカイブ) [中國翻譯] [無修正]"

        oname："喂我吃吧 老師!"

        :return: 返回本子的原始名称
        """
        ...
    
    @property
    def authoroname(self): # -> str:
        """
        authoroname = author + oname

        个人认为识别度比较高的本子名称，一眼看去就能获取到本子的关键信息

        具体格式: '【author】oname'

        示例:

        Pname：喂我吃吧 老師! [欶瀾漢化組] [BLVEFO9] たべさせて、せんせい! (ブルーアーカイブ) [中國翻譯] [無修正]

        Pauthoroname：【BLVEFO9】喂我吃吧 老師!

        :return: 返回作者名+本子原始名称，格式为: '【author】oname'
        """
        ...
    
    @property
    def idoname(self): # -> str:
        """
        类似 authoroname
        
        :return: '[id] oname'
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    @classmethod
    def __alias__(cls): # -> str:
        ...
    
    @classmethod
    def get_dirname(cls, detail: DetailEntity, ref: str) -> str:
        """
        该方法被 DirDule 调用，用于生成特定层次的文件夹

        通常调用方式如下:
        Atitle -> ref = 'title' -> DetailEntity.get_dirname(album, 'title')
        该方法需要返回 ref 对应的文件夹名，默认实现直接返回 getattr(detail, 'title')

        用户可重写此方法，来实现自定义文件夹名

        v2.4.5: 此方法支持优先从 JmModuleConfig.XFIELD_ADVICE 中获取自定义函数并调用返回结果

        :param detail: 本子/章节 实例
        :param ref: 字段名
        :returns: 文件夹名
        """
        ...
    
    def get_properties_dict(self): # -> dict[Any, Any]:
        ...
    


class JmImageDetail(JmBaseEntity, Downloadable):
    def __init__(self, aid, scramble_id, img_url, img_file_name, img_file_suffix, from_photo=..., query_params=..., index=...) -> None:
        ...
    
    @property
    def filename_without_suffix(self): # -> str:
        ...
    
    @property
    def filename(self): # -> str:
        ...
    
    @property
    def is_gif(self): # -> bool:
        ...
    
    @property
    def download_url(self) -> str:
        """
        图片的下载路径
        与 self.img_url 的唯一不同是，在最后会带上 ?{self.query_params}
        :returns: 图片的下载路径
        """
        ...
    
    @classmethod
    def of(cls, photo_id: str, scramble_id: str, data_original: str, from_photo=..., query_params=..., index=...) -> JmImageDetail:
        """
        该方法用于创建 JmImageDetail 对象
        """
        ...
    
    @property
    def tag(self) -> str:
        """
        this tag is used to print pretty info when logging
        """
        ...
    
    @classmethod
    def is_image(cls): # -> Literal[True]:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...


class JmPhotoDetail(DetailEntity, Downloadable):
    def __init__(self, photo_id, name, series_id, sort, tags=..., scramble_id=..., page_arr=..., data_original_domain=..., data_original_0=..., author=..., from_album=...) -> None:
        ...
    
    @property
    def is_single_album(self) -> bool:
        ...
    
    @property
    def tags(self) -> List[str]:
        ...
    
    @property
    def indextitle(self): # -> str:
        ...
    
    @property
    def album_id(self) -> str:
        ...
    
    @property
    def album_index(self) -> int:
        """
        返回这个章节在本子中的序号，从1开始
        """
        ...
    
    @property
    def author(self) -> str:
        ...
    
    def create_image_detail(self, index) -> JmImageDetail:
        ...
    
    def get_img_data_original(self, img_name: str) -> str:
        """
        根据图片名，生成图片的完整请求路径 URL
        例如：img_name = 01111.webp
        返回：https://cdn-msp2.18comic.org/media/photos/147643/01111.webp
        """
        ...
    
    def get_data_original_query_params(self, data_original_0: Optional[str]) -> str:
        ...
    
    @property
    def id(self): # -> str:
        ...
    
    @lru_cache(None)
    def getindex(self, index) -> JmImageDetail:
        ...
    
    def __getitem__(self, item) -> Union[JmImageDetail, List[JmImageDetail]]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __iter__(self) -> Generator[JmImageDetail, None, None]:
        ...
    
    @classmethod
    def is_photo(cls): # -> Literal[True]:
        ...
    


class JmAlbumDetail(DetailEntity, Downloadable):
    def __init__(self, album_id, scramble_id, name, episode_list, page_count, pub_date, update_date, likes, views, comment_count, works, actors, authors, tags, related_list=..., description=...) -> None:
        ...
    
    @property
    def author(self): # -> str:
        """
        作者
        禁漫本子的作者标签可能有多个，全部作者请使用字段 self.author_list
        """
        ...
    
    @property
    def id(self): # -> str:
        ...
    
    @staticmethod
    def distinct_episode(episode_list: list): # -> list[Any]:
        """
        去重章节
        photo_id, photo_index, photo_title, photo_pub_date
        """
        ...
    
    def create_photo_detail(self, index) -> JmPhotoDetail:
        ...
    
    @lru_cache(None)
    def getindex(self, item) -> JmPhotoDetail:
        ...
    
    def __getitem__(self, item) -> Union[JmPhotoDetail, List[JmPhotoDetail]]:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __iter__(self) -> Generator[JmPhotoDetail, None, None]:
        ...
    
    @classmethod
    def is_album(cls): # -> Literal[True]:
        ...
    


class JmPageContent(JmBaseEntity, IndexedEntity):
    ContentItem = Tuple[str, Dict[str, Any]]
    def __init__(self, content: List[ContentItem], total: int) -> None:
        """
        content:
        [
          album_id, {title, tags, ...}
        ]
        :param content: 分页数据
        :param total: 总结果数
        """
        ...
    
    @property
    def page_count(self) -> int:
        """
        页数
        """
        ...
    
    @property
    def page_size(self) -> int:
        """
        页大小
        """
        ...
    
    def iter_id(self) -> Generator[str, None, None]:
        """
        返回 album_id 的迭代器
        """
        ...
    
    def iter_id_title(self) -> Generator[Tuple[str, str], None, None]:
        """
        返回 album_id, album_title 的迭代器
        """
        ...
    
    def iter_id_title_tag(self) -> Generator[Tuple[str, str, List[str]], None, None]:
        """
        返回 album_id, album_title, album_tags 的迭代器
        """
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __iter__(self): # -> Generator[Tuple[str, str], None, None]:
        ...
    
    def __getitem__(self, item) -> Union[ContentItem, List[ContentItem]]:
        ...
    
    def getindex(self, index: int): # -> ContentItem:
        ...
    
    @classmethod
    def is_page(cls): # -> Literal[True]:
        ...
    


class JmSearchPage(JmPageContent):
    @property
    def page_size(self) -> int:
        ...
    
    @property
    def is_single_album(self): # -> bool:
        ...
    
    @property
    def single_album(self) -> JmAlbumDetail:
        ...
    
    @classmethod
    def wrap_single_album(cls, album: JmAlbumDetail) -> JmSearchPage:
        ...
    


JmCategoryPage = JmSearchPage
class JmFavoritePage(JmPageContent):
    def __init__(self, content, folder_list, total) -> None:
        """

        :param content: 收藏夹一页数据
        :param folder_list: 所有的收藏夹的信息
        :param total: 收藏夹的收藏总数
        """
        ...
    
    @property
    def page_size(self) -> int:
        ...
    
    def iter_folder_id_name(self) -> Generator[Tuple[str, str], None, None]:
        """
        用户文件夹的迭代器
        """
        ...
    


