"""
This type stub file was generated by pyright.
"""

from .jm_client_impl import *

class CacheRegistry:
    REGISTRY = ...
    @classmethod
    def level_option(cls, option, _client):
        ...
    
    @classmethod
    def level_client(cls, _option, client):
        ...
    
    @classmethod
    def enable_client_cache_on_condition(cls, option: JmOption, client: JmcomicClient, cache: Union[None, bool, str, Callable]): # -> None:
        """
        cache parameter

        if None: no cache

        if bool:
          true: level_option

          false: no cache

        if str:
          (invoke corresponding Cache class method)

        :param option: JmOption
        :param client: JmcomicClient
        :param cache: config dsl
        """
        ...
    


class DirRule:
    RULE_BASE_DIR = ...
    def __init__(self, rule: str, base_dir=..., normalize_zh=...) -> None:
        """
        :param rule: DSL rule
        :param base_dir: base directory
        :param normalize_zh: 'zh-cn'|'zh-tw'| or None. 控制是否以及如何进行繁简体归一化，默认 None
        """
        ...
    
    def decide_image_save_dir(self, album: JmAlbumDetail, photo: JmPhotoDetail) -> str:
        ...
    
    def decide_album_root_dir(self, album: JmAlbumDetail) -> str:
        ...
    
    def apply_rule_to_path(self, album, photo, only_album_rules=...) -> str:
        ...
    
    def get_rule_parser_list(self, rule_dsl: str): # -> list[Any]:
        """
        解析下载路径dsl，得到一个路径规则解析列表
        """
        ...
    
    def parse_bd_rule(self, album, photo, rule): # -> str:
        ...
    
    @classmethod
    def parse_f_string_rule(cls, album, photo, rule: str): # -> str:
        ...
    
    @classmethod
    def parse_detail_rule(cls, album, photo, rule: str): # -> str:
        ...
    
    def split_rule_dsl(self, rule_dsl: str) -> List[str]:
        ...
    
    @classmethod
    def get_rule_parser(cls, rule: str): # -> Callable[..., str]:
        ...
    
    @classmethod
    def apply_rule_to_filename(cls, album, photo, rule: str) -> str:
        ...
    


class JmOption:
    def __init__(self, dir_rule: Dict, download: Dict, client: Dict, plugins: Dict, filepath=..., call_after_init_plugin=...) -> None:
        ...
    
    def copy_option(self): # -> Self:
        ...
    
    def decide_image_batch_count(self, photo: JmPhotoDetail): # -> list[AdvancedDict | Any] | AdvancedDict:
        ...
    
    def decide_photo_batch_count(self, album: JmAlbumDetail): # -> list[AdvancedDict | Any] | AdvancedDict:
        ...
    
    def decide_image_filename(self, image: JmImageDetail) -> str:
        """
        返回图片的文件名，不包含后缀
        默认返回禁漫的图片文件名，例如：00001 (.jpg)
        """
        ...
    
    def decide_image_suffix(self, image: JmImageDetail) -> str:
        """
        返回图片的后缀，如果返回的后缀和原后缀不一致，则会进行图片格式转换
        """
        ...
    
    def decide_image_save_dir(self, photo, ensure_exists=...) -> str:
        ...
    
    def decide_image_filepath(self, image: JmImageDetail, consider_custom_suffix=...) -> str:
        ...
    
    def decide_download_cache(self, _image: JmImageDetail) -> bool:
        ...
    
    def decide_download_image_decode(self, image: JmImageDetail) -> bool:
        ...
    
    @classmethod
    def default_dict(cls) -> Dict:
        ...
    
    @classmethod
    def default(cls) -> JmOption:
        """
        使用默认的 JmOption
        """
        ...
    
    @classmethod
    def construct(cls, origdic: Dict, cover_default=...) -> JmOption:
        ...
    
    @classmethod
    def compatible_with_old_versions(cls, dic): # -> None:
        """
        兼容旧的option版本
        """
        ...
    
    def deconstruct(self) -> Dict:
        ...
    
    @classmethod
    def from_file(cls, filepath: str) -> JmOption:
        ...
    
    def to_file(self, filepath=...): # -> None:
        ...
    
    @field_cache()
    def build_jm_client(self, **kwargs): # -> JmHtmlClient | JmApiClient:
        """
        该方法会首次调用会创建JmcomicClient对象，
        然后保存在self中，
        多次调用`不会`创建新的JmcomicClient对象
        """
        ...
    
    def new_jm_client(self, domain_list=..., impl=..., cache=..., domain_retry_strategy=..., **kwargs) -> Union[JmHtmlClient, JmApiClient]:
        """
        创建新的Client（客户端），不同Client之间的元数据不共享
        """
        ...
    
    def update_cookies(self, cookies: dict): # -> None:
        ...
    
    def decide_client_domain(self, client_key: str) -> List[str]:
        ...
    
    @classmethod
    def client_key_is_given_type(cls, client_key, ctype: Type[JmcomicClient]): # -> bool:
        ...
    
    @classmethod
    def merge_default_dict(cls, user_dict, default_dict=...): # -> Dict[Any, Any]:
        """
        深度合并两个字典
        """
        ...
    
    def download_album(self, album_id, downloader=..., callback=...): # -> None:
        ...
    
    def download_photo(self, photo_id, downloader=..., callback=...): # -> None:
        ...
    
    def call_all_plugin(self, group: str, safe=..., **extra): # -> None:
        ...
    
    def invoke_plugin(self, pclass, kwargs: Optional[Dict], extra: dict, pinfo: dict): # -> None:
        ...
    
    def handle_plugin_valid_exception(self, e, pinfo: dict, kwargs: dict, _plugin, _pclass): # -> None:
        ...
    
    def handle_plugin_unexpected_error(self, e, pinfo: dict, kwargs: dict, _plugin, pclass):
        ...
    
    def handle_plugin_jmcomic_exception(self, e, pinfo: dict, kwargs: dict, _plugin, pclass):
        ...
    
    def fix_kwargs(self, kwargs: Optional[Dict]) -> Dict[str, Any]:
        """
        kwargs将来要传给方法参数，这要求kwargs的key是str类型，
        该方法检查kwargs的key的类型，如果不是str，尝试转为str，不行则抛异常。
        """
        ...
    
    def wait_all_plugins_finish(self): # -> None:
        ...
    


