"""
This type stub file was generated by pyright.
"""

from .jm_option import *

"""
该文件存放的是option插件
"""
class PluginValidationException(Exception):
    def __init__(self, plugin: JmOptionPlugin, msg: str) -> None:
        ...
    


class JmOptionPlugin:
    plugin_key: str
    def __init__(self, option: JmOption) -> None:
        ...
    
    def invoke(self, **kwargs) -> None:
        """
        执行插件的功能
        :param kwargs: 给插件的参数
        """
        ...
    
    @classmethod
    def build(cls, option: JmOption) -> JmOptionPlugin:
        """
        创建插件实例
        :param option: JmOption对象
        """
        ...
    
    def log(self, msg, topic=...): # -> None:
        ...
    
    def require_param(self, case: Any, msg: str): # -> None:
        """
        专门用于校验参数的方法，会抛出特定异常，由option拦截根据策略进行处理

        :param case: 条件
        :param msg: 报错信息
        """
        ...
    
    def warning_lib_not_install(self, lib: str, throw=...): # -> None:
        ...
    
    def execute_deletion(self, paths: List[str]): # -> None:
        """
        删除文件和文件夹
        :param paths: 路径列表
        """
        ...
    
    def execute_cmd(self, cmd): # -> int:
        """
        执行shell命令，这里采用简单的实现
        :param cmd: shell命令
        """
        ...
    
    def execute_multi_line_cmd(self, cmd: str): # -> None:
        ...
    
    def enter_wait_list(self): # -> None:
        ...
    
    def leave_wait_list(self): # -> None:
        ...
    
    def wait_until_finish(self): # -> None:
        ...
    
    def decide_filepath(self, album: Optional[JmAlbumDetail], photo: Optional[JmPhotoDetail], filename_rule: Optional[str], suffix: Optional[str], base_dir: Optional[str], dir_rule_dict: Optional[dict]): # -> str:
        """
        根据规则计算一个文件的全路径

        参数 dir_rule_dict 优先级最高，
        如果 dir_rule_dict 不为空，优先用 dir_rule_dict
        否则使用 base_dir + filename_rule + suffix
        """
        ...
    


class JmLoginPlugin(JmOptionPlugin):
    """
    功能：登录禁漫，并保存登录后的cookies，让所有client都带上此cookies
    """
    plugin_key = ...
    def invoke(self, username: str, password: str, impl=...) -> None:
        ...
    


class UsageLogPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, **kwargs) -> None:
        ...
    
    def set_thread_as_option_attr(self, t): # -> None:
        """
        线程留痕
        """
        ...
    
    def monitor_resource_usage(self, interval=..., enable_warning=..., warning_cpu_percent=..., warning_mem_percent=..., warning_thread_count=...): # -> None:
        ...
    


class FindUpdatePlugin(JmOptionPlugin):
    """
    参考: https://github.com/hect0x7/JMComic-Crawler-Python/issues/95
    """
    plugin_key = ...
    def invoke(self, **kwargs) -> None:
        ...
    
    def download_album_with_find_update(self, dic: Dict[str, int]): # -> None:
        class FindUpdateDownloader(JmDownloader):
            ...
        
        
    


class ZipPlugin(JmOptionPlugin):
    """
    感谢zip加密功能的贡献者:
        - AXIS5 a.k.a AXIS5Hacker (https://github.com/hect0x7/JMComic-Crawler-Python/pull/375)
    """
    plugin_key = ...
    def invoke(self, downloader, album: JmAlbumDetail = ..., photo: JmPhotoDetail = ..., delete_original_file=..., level=..., filename_rule=..., suffix=..., zip_dir=..., dir_rule=..., encrypt=...) -> None:
        ...
    
    def get_downloaded_photo(self, downloader, album, photo):
        ...
    
    def zip_photo(self, photo, image_list: list, zip_path: str, path_to_delete, encrypt_dict): # -> None:
        """
        压缩photo文件夹
        """
        ...
    
    @staticmethod
    def unified_path(f): # -> str:
        ...
    
    def zip_album(self, album, photo_dict: dict, zip_path, path_to_delete, encrypt_dict): # -> None:
        """
        压缩album文件夹
        """
        ...
    
    def after_zip(self, path_to_delete: List[str]): # -> None:
        ...
    
    @classmethod
    def generate_random_str(cls, random_length) -> str:
        """
        自动生成随机字符密码，长度由randomlength指定
        """
        ...
    
    def open_zip_file(self, zip_path: str, encrypt_dict: Optional[dict]): # -> ZipFile:
        ...
    
    def decide_password(self, encrypt_dict: dict, zip_path: str): # -> tuple[str, bool]:
        ...
    


class ClientProxyPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, proxy_client_key, whitelist=..., **clazz_init_kwargs) -> None:
        ...
    


class ImageSuffixFilterPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, allowed_orig_suffix=...) -> None:
        ...
    


class SendQQEmailPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, msg_from, msg_to, password, title, content, album=..., downloader=...) -> None:
        ...
    


class LogTopicFilterPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, whitelist) -> None:
        ...
    


class AutoSetBrowserCookiesPlugin(JmOptionPlugin):
    plugin_key = ...
    accepted_cookies_keys = ...
    def invoke(self, browser: str, domain: str) -> None:
        """
        坑点预警：由于禁漫需要校验同一设备，使用该插件需要配置自己浏览器的headers，例如

        ```yml
        client:
          postman:
            meta_data:
              headers: {
               # 浏览器headers
              }

        # 插件配置如下：
        plugins:
          after_init:
            - plugin: auto_set_browser_cookies
              kwargs:
                browser: chrome
                domain: 18comic.vip
        ```

        :param browser: chrome/edge/...
        :param domain: 18comic.vip/...
        :return: cookies
        """
        ...
    


class FavoriteFolderExportPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, save_dir=..., zip_enable=..., zip_filepath=..., zip_password=..., delete_original_file=...): # -> None:
        ...
    
    def main(self): # -> None:
        ...
    
    def handle_folder(self, fid: str, fname: str): # -> None:
        ...
    
    def fetch_folder_page_data(self, fid): # -> list[JmFavoritePage]:
        ...
    
    def save_folder_page_data_to_file(self, page_data: List[JmFavoritePage], fid: str, fname: str): # -> str | None:
        ...
    
    def zip_folder_without_password(self, files, zip_path): # -> None:
        """
        压缩文件夹中的文件并设置密码

        :param files: 要压缩的文件的绝对路径的列表
        :param zip_path: 压缩文件的保存路径
        """
        ...
    
    def zip_with_password(self): # -> None:
        ...
    


class Img2pdfPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, photo: JmPhotoDetail = ..., album: JmAlbumDetail = ..., downloader=..., pdf_dir=..., filename_rule=..., dir_rule=..., delete_original_file=..., encrypt=..., **kwargs): # -> None:
        ...
    
    def write_img_2_pdf(self, pdf_filepath, album: JmAlbumDetail, photo: JmPhotoDetail, encrypt): # -> tuple[list[Any], list[str]]:
        ...
    
    def encrypt_pdf(self, pdf_filepath: str, encrypt: dict): # -> None:
        ...
    


class LongImgPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, photo: JmPhotoDetail = ..., album: JmAlbumDetail = ..., downloader=..., img_dir=..., filename_rule=..., delete_original_file=..., dir_rule=..., **kwargs): # -> None:
        ...
    
    def write_img_2_long_img(self, long_img_path, album: JmAlbumDetail, photo: JmPhotoDetail) -> List[str]:
        ...
    
    def open_images(self, img_paths: List[str]): # -> list[Any]:
        ...
    


class JmServerPlugin(JmOptionPlugin):
    plugin_key = ...
    default_run_kwargs = ...
    single_instance_lock = ...
    def __init__(self, option: JmOption) -> None:
        ...
    
    def invoke(self, password=..., base_dir=..., album=..., photo=..., downloader=..., run=..., **kwargs): # -> None:
        """

        :param password: 密码
        :param base_dir: 初始访问服务器的根路径
        :param album: 为了支持 after_album 这种调用时机
        :param photo: 为了支持 after_album 这种调用时机
        :param downloader: 为了支持 after_album 这种调用时机
        :param run: 用于启动服务器: app.run(**run_kwargs)
        :param kwargs: 用于JmServer构造函数: JmServer(base_dir, password, **kwargs)
        """
        ...
    
    def warning_wrong_usage_of_debug(self): # -> None:
        ...
    
    def wait_server_stop(self, proactive=...): # -> None:
        ...
    
    def wait_until_finish(self): # -> None:
        ...
    
    @classmethod
    def build(cls, option: JmOption) -> JmOptionPlugin:
        """
        单例模式
        """
        ...
    


class SubscribeAlbumUpdatePlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, album_photo_dict=..., email_notify=..., download_if_has_update=..., auto_update_after_download=...) -> None:
        ...
    
    def check_photo_update(self, album_id: str, photo_id: str): # -> tuple[bool, list[Any]]:
        ...
    


class SkipPhotoWithFewImagesPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, at_least_image_count: int, photo: Optional[JmPhotoDetail] = ..., image: Optional[JmImageDetail] = ..., album: Optional[JmAlbumDetail] = ..., **kwargs): # -> None:
        ...
    
    def try_mark_photo_skip_and_log(self, photo: JmPhotoDetail, at_least_image_count: int): # -> None:
        ...
    
    @classmethod
    @field_cache()
    def build(cls, option: JmOption) -> JmOptionPlugin:
        ...
    


class DeleteDuplicatedFilesPlugin(JmOptionPlugin):
    """
    https://github.com/hect0x7/JMComic-Crawler-Python/issues/244
    """
    plugin_key = ...
    @classmethod
    def calculate_md5(cls, file_path): # -> str:
        ...
    
    @classmethod
    def find_duplicate_files(cls, root_folder): # -> defaultdict[Any, list[Any]]:
        """递归读取文件夹下所有文件并计算MD5出现次数"""
        ...
    
    def invoke(self, limit, album=..., downloader=..., delete_original_file=..., **kwargs) -> None:
        ...
    
    def find_duplicated_files_and_delete(self, limit: int, root_folder: str, album: Optional[JmAlbumDetail] = ...): # -> None:
        ...
    


class ReplacePathStringPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, replace: Dict[str, str]): # -> None:
        ...
    


class AdvancedRetryPlugin(JmOptionPlugin):
    plugin_key = ...
    def __init__(self, option: JmOption) -> None:
        ...
    
    def invoke(self, retry_config, **kwargs): # -> None:
        ...
    
    def __call__(self, client: AbstractJmClient, *args, **kwargs): # -> JmImageResp | None:
        ...
    
    def request_with_retry(self, client: AbstractJmClient, request: Callable, url: str, is_image: bool, **kwargs): # -> JmImageResp:
        """
        实现如下域名重试机制：
        - 对域名列表轮询请求，配置：retry_rounds
        - 限制单个域名最大失败次数，配置：retry_domain_max_times
        - 轮询域名列表前，根据历史失败次数对域名列表排序，失败多的后置
        """
        ...
    
    def get_sorted_domain(self, client: JmcomicClient, times): # -> list[Any]:
        ...
    
    def update_failed_count(self, client: AbstractJmClient, domain: str): # -> None:
        ...
    
    @staticmethod
    def failed_count(client: JmcomicClient, domain: str) -> int:
        ...
    


class DownloadCoverPlugin(JmOptionPlugin):
    plugin_key = ...
    def invoke(self, dir_rule: dict, size=..., photo: JmPhotoDetail = ..., album: JmAlbumDetail = ..., downloader=..., **kwargs) -> None:
        ...
    


