"""
This type stub file was generated by pyright.
"""

from PIL import Image
from .jm_exception import *

class JmcomicText:
    pattern_jm_domain = ...
    pattern_jm_pa_id = ...
    pattern_html_jm_pub_domain = ...
    pattern_html_photo_photo_id = ...
    pattern_html_photo_scramble_id = ...
    pattern_html_photo_name = ...
    pattern_html_photo_data_original_domain = ...
    pattern_html_photo_data_original_0 = ...
    pattern_html_photo_tags = ...
    pattern_html_photo_series_id = ...
    pattern_html_photo_sort = ...
    pattern_html_photo_page_arr = ...
    pattern_html_b64_decode_content = ...
    pattern_html_album_album_id = ...
    pattern_html_album_scramble_id = ...
    pattern_html_album_name = ...
    pattern_html_album_description = ...
    pattern_html_album_episode_list = ...
    pattern_html_album_page_count = ...
    pattern_html_album_pub_date = ...
    pattern_html_album_update_date = ...
    pattern_html_tag_a = ...
    pattern_html_album_works = ...
    pattern_html_album_actors = ...
    pattern_html_album_tags = ...
    pattern_html_album_authors = ...
    pattern_html_album_likes = ...
    pattern_html_album_views = ...
    pattern_html_album_comment_count = ...
    pattern_ajax_favorite_msg = ...
    pattern_api_response_json_object = ...
    @classmethod
    def parse_to_jm_domain(cls, text: str): # -> str | Any:
        ...
    
    @classmethod
    def parse_to_jm_id(cls, text) -> str:
        ...
    
    @classmethod
    def analyse_jm_pub_html(cls, html: str, domain_keyword=...) -> List[str]:
        ...
    
    @classmethod
    def parse_jm_base64_html(cls, resp_text: str) -> str:
        ...
    
    @classmethod
    def analyse_jm_photo_html(cls, html: str) -> JmPhotoDetail:
        ...
    
    @classmethod
    def analyse_jm_album_html(cls, html: str) -> JmAlbumDetail:
        ...
    
    @classmethod
    def reflect_new_instance(cls, html: str, cls_field_prefix: str, clazz: type): # -> Any:
        ...
    
    @classmethod
    def format_url(cls, path, domain): # -> str:
        ...
    
    @classmethod
    def format_album_url(cls, aid, domain=...): # -> str:
        """
        把album_id变为可访问的URL，方便print打印后用浏览器访问
        """
        ...
    
    class DSLReplacer:
        def __init__(self) -> None:
            ...
        
        def parse_dsl_text(self, text) -> str:
            ...
        
        def add_dsl_and_replacer(self, dsl: str, replacer: Callable[[Match], str]): # -> None:
            ...
        
    
    
    @classmethod
    def match_os_env(cls, match: Match) -> str:
        ...
    
    dsl_replacer = ...
    @classmethod
    def parse_to_abspath(cls, dsl_text: str) -> str:
        ...
    
    @classmethod
    def parse_dsl_text(cls, dsl_text: str) -> str:
        ...
    
    bracket_map = ...
    @classmethod
    def parse_orig_album_name(cls, name: str, default=...): # -> str | None:
        ...
    
    @classmethod
    def tokenize(cls, title: str) -> List[str]:
        """
        繞道#2 [暴碧漢化組] [えーすけ（123）] よりみち#2 (COMIC 快樂天 2024年1月號) [中國翻譯] [DL版]
        :return: ['繞道#2', '[暴碧漢化組]', '[えーすけ（123）]', 'よりみち#2', '(COMIC 快樂天 2024年1月號)', '[中國翻譯]', '[DL版]']
        """
        ...
    
    @classmethod
    def to_zh_cn(cls, s):
        ...
    
    @classmethod
    def to_zh(cls, s, target=...):
        """
        通用的繁简体转换接口。

        :param s: 待转换字符串
        :param target: 目标编码: 'zh-cn'（简体）, 'zh-tw'（繁体），或 None 表示不转换
        :return: 转换后的字符串（若转换失败或未安装 zhconv，返回原始字符串）
        """
        ...
    
    @classmethod
    def try_mkdir(cls, save_dir: str): # -> str:
        ...
    
    @classmethod
    def try_parse_json_object(cls, resp_text: str) -> dict:
        ...
    
    @classmethod
    def limit_text(cls, text: str, limit: int) -> str:
        ...
    
    @classmethod
    def get_album_cover_url(cls, album_id: Union[str, int], image_domain: Optional[str] = ..., size: str = ...) -> str:
        """
        根据本子id生成封面url

        :param album_id: 本子id
        :param image_domain: 图片cdn域名（可传入裸域或含协议的域名）
        :param size: 尺寸后缀，例如搜索列表页会使用 size="_3x4" 的封面图
        """
        ...
    


class PatternTool:
    @classmethod
    def match_or_default(cls, html: str, pattern: Pattern, default): # -> str | Any:
        ...
    
    @classmethod
    def require_match(cls, html: str, pattern: Pattern, msg, rindex=...): # -> str | Any | Match[str]:
        ...
    
    @classmethod
    def require_not_match(cls, html: str, pattern: Pattern, *, msg_func): # -> None:
        ...
    


class JmPageTool:
    pattern_html_search_shorten_for = ...
    pattern_html_search_album_info_list = ...
    pattern_html_category_album_info_list = ...
    pattern_html_search_tags = ...
    pattern_html_search_error = ...
    pattern_html_search_total = ...
    pattern_html_favorite_content = ...
    pattern_html_favorite_total = ...
    pattern_html_favorite_folder_list = ...
    @classmethod
    def parse_html_to_search_page(cls, html: str) -> JmSearchPage:
        ...
    
    @classmethod
    def parse_html_to_category_page(cls, html: str) -> JmSearchPage:
        ...
    
    @classmethod
    def parse_html_to_favorite_page(cls, html: str) -> JmFavoritePage:
        ...
    
    @classmethod
    def parse_api_to_search_page(cls, data: AdvancedDict) -> JmSearchPage:
        """
        model_data: {
          "search_query": "MANA",
          "total": "177",
          "content": [
            {
              "id": "441923",
              "author": "MANA",
              "description": "",
              "name": "[MANA] 神里绫华5",
              "image": "",
              "category": {
                "id": "1",
                "title": "同人"
              },
              "category_sub": {
                "id": "1",
                "title": "同人"
              }
            }
          ]
        }
        """
        ...
    
    @classmethod
    def parse_api_to_favorite_page(cls, data: AdvancedDict) -> JmFavoritePage:
        """
        {
          "list": [
            {
              "id": "363859",
              "author": "紺菓",
              "description": "",
              "name": "[無邪氣漢化組] (C99) [紺色果實 (紺菓)] サレンの樂しい夢 (プリンセスコネクト!Re:Dive) [中國翻譯]",
              "latest_ep": null,
              "latest_ep_aid": null,
              "image": "",
              "category": {
                "id": "1",
                "title": "同人"
              },
              "category_sub": {
                "id": "1",
                "title": "同人"
              }
            }
          ],
          "folder_list": [
            {
              "0": "123",
              "FID": "123",
              "1": "456",
              "UID": "456",
              "2": "收藏夹名",
              "name": "收藏夹名"
            }
          ],
          "total": "87",
          "count": 20
        }
        """
        ...
    
    @classmethod
    def adapt_content(cls, content): # -> list[tuple[Any, dict[Any, Any]]]:
        ...
    


class JmApiAdaptTool:
    """
    本类负责把移动端的api返回值，适配为标准的实体类

    # album
    {
      "id": 123,
      "name": "[狗野叉漢化]",
      "author": [
        "AREA188"
      ],
      "images": [
        "00004.webp"
      ],
      "description": null,
      "total_views": "41314",
      "likes": "918",
      "series": [],
      "series_id": "0",
      "comment_total": "5",
      "tags": [
        "全彩",
        "中文"
      ],
      "works": [],
      "actors": [],
      "related_list": [
        {
          "id": "333718",
          "author": "been",
          "description": "",
          "name": "[been]The illusion of lies（1）[中國語][無修正][全彩]",
          "image": ""
        }
      ],
      "liked": false,
      "is_favorite": false
    }

    # photo
    {
      "id": 413446,
      "series": [
        {
          "id": "487043",
          "name": "第48話",
          "sort": "48"
        }
      ],
      "tags": "慾望 調教 NTL 地鐵 戲劇",
      "name": "癡漢成癮-第2話",
      "images": [
        "00047.webp"
      ],
      "series_id": "400222",
      "is_favorite": false,
      "liked": false
    }
    """
    field_adapter = ...
    @classmethod
    def parse_entity(cls, data: dict, clazz: type): # -> Any | JmAlbumDetail:
        ...
    
    @classmethod
    def get_adapter(cls, clazz: type): # -> list[Any]:
        ...
    
    @classmethod
    def post_adapt_album(cls, data: dict, _clazz: type, fields: dict): # -> None:
        ...
    
    @classmethod
    def post_adapt_photo(cls, data: dict, _clazz: type, fields: dict): # -> None:
        ...
    


class JmImageTool:
    @classmethod
    def save_resp_img(cls, resp: Any, filepath: str, need_convert=...): # -> None:
        """
        接收HTTP响应对象，将其保存到图片文件.
        如果需要改变图片的文件格式，比如 .jpg → .png，则需要指定参数 neet_convert=True.
        如果不需要改变图片的文件格式，使用 need_convert=False，可以跳过PIL解析图片，效率更高.

        :param resp: JmImageResp
        :param filepath: 图片文件路径
        :param need_convert: 是否转换图片
        """
        ...
    
    @classmethod
    def save_image(cls, image: Image, filepath: str): # -> None:
        """
        保存图片

        :param image: PIL.Image对象
        :param filepath: 保存文件路径
        """
        ...
    
    @classmethod
    def save_directly(cls, resp, filepath): # -> None:
        ...
    
    @classmethod
    def decode_and_save(cls, num: int, img_src: Image, decoded_save_path: str) -> None:
        """
        解密图片并保存
        :param num: 分割数，可以用 cls.calculate_segmentation_num 计算
        :param img_src: 原始图片
        :param decoded_save_path: 解密图片的保存路径
        """
        ...
    
    @classmethod
    def open_image(cls, fp: Union[str, bytes]): # -> ImageFile:
        ...
    
    @classmethod
    def get_num(cls, scramble_id, aid, filename: str) -> int:
        """
        获得图片分割数
        """
        ...
    
    @classmethod
    def get_num_by_url(cls, scramble_id, url) -> int:
        """
        获得图片分割数
        """
        ...
    
    @classmethod
    def get_num_by_detail(cls, detail: JmImageDetail) -> int:
        """
        获得图片分割数
        """
        ...
    


class JmCryptoTool:
    """
    禁漫加解密相关逻辑
    """
    @classmethod
    def token_and_tokenparam(cls, ts, ver=..., secret=...): # -> tuple[str, str]:
        """
        计算禁漫接口的请求headers的token和tokenparam

        :param ts: 时间戳
        :param ver: app版本
        :param secret: 密钥
        :return (token, tokenparam)
        """
        ...
    
    @classmethod
    def decode_resp_data(cls, data: str, ts, secret=...) -> str:
        """
        解密接口返回值

        :param data: resp.json()['data']
        :param ts: 时间戳
        :param secret: 密钥
        :return: json格式的字符串
        """
        ...
    
    @classmethod
    def md5hex(cls, key: str): # -> str:
        ...
    


